#!/usr/bin/env python3
"""
Fetch all GitHub followers for NhanAZ and update the README.md
with a visual table of follower avatars and usernames.

This script uses only the Python standard library — no pip install needed.
"""

import json
import os
import re
import sys
import urllib.request

GITHUB_USER = "NhanAZ"
README_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "README.md")
COLUMNS = 7
AVATAR_SIZE = 64

MARKERS_START = "<!-- FOLLOWERS-START -->"
MARKERS_END = "<!-- FOLLOWERS-END -->"


def fetch_all_followers(username: str, token: str | None = None) -> list[dict]:
    """Fetch all followers with pagination (100 per page)."""
    followers = []
    page = 1
    per_page = 100

    while True:
        url = f"https://api.github.com/users/{username}/followers?per_page={per_page}&page={page}"
        req = urllib.request.Request(url)
        req.add_header("Accept", "application/vnd.github.v3+json")
        req.add_header("User-Agent", f"{username}-readme-updater")
        if token:
            req.add_header("Authorization", f"Bearer {token}")

        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read().decode("utf-8"))

        if not data:
            break

        followers.extend(data)
        page += 1

    return followers


def generate_followers_table(followers: list[dict]) -> str:
    """Generate an HTML table of followers with avatars."""
    # GitHub API returns followers in chronological order (oldest first)
    # No sorting needed — the API order is exactly what we want

    lines = []
    lines.append(MARKERS_START)
    lines.append("<!-- This section is auto-generated by a GitHub Actions workflow. Do not edit manually. -->")
    lines.append("")
    lines.append(f"**{len(followers)}** amazing people are following me! 🎉")
    lines.append("")
    lines.append("<table>")

    for i in range(0, len(followers), COLUMNS):
        row = followers[i : i + COLUMNS]

        # Avatar row
        lines.append("  <tr>")
        for follower in row:
            login = follower["login"]
            avatar = follower["avatar_url"]
            profile = f"https://github.com/{login}"
            lines.append(
                f'    <td align="center">'
                f'<a href="{profile}">'
                f'<img src="{avatar}" width="{AVATAR_SIZE}" height="{AVATAR_SIZE}" alt="@{login}"/>'
                f"<br />"
                f"<sub><b>@{login}</b></sub>"
                f"</a>"
                f"</td>"
            )
        lines.append("  </tr>")

    lines.append("</table>")
    lines.append("")
    lines.append(MARKERS_END)

    return "\n".join(lines)


def update_readme(table_content: str) -> bool:
    """Update README.md between the marker comments. Returns True if changed."""
    with open(README_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    pattern = re.compile(
        re.escape(MARKERS_START) + r".*?" + re.escape(MARKERS_END),
        re.DOTALL,
    )

    if pattern.search(content):
        new_content = pattern.sub(table_content, content)
    else:
        print("WARNING: Markers not found in README.md. Cannot update.")
        return False

    if new_content == content:
        print("No changes detected. README is already up to date.")
        return False

    with open(README_PATH, "w", encoding="utf-8") as f:
        f.write(new_content)

    print("README.md updated successfully.")
    return True


def main():
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("Note: GITHUB_TOKEN not set. Using unauthenticated requests (lower rate limit).")

    print(f"Fetching followers for {GITHUB_USER}...")
    followers = fetch_all_followers(GITHUB_USER, token)
    print(f"Found {len(followers)} followers.")

    table = generate_followers_table(followers)
    changed = update_readme(table)

    if not changed:
        print("No update needed.")
    else:
        print("README.md has been updated with the latest followers.")


if __name__ == "__main__":
    main()
