#!/usr/bin/env python3
"""
Fetch all GitHub followers for NhanAZ and update the README.md
with a visual table of follower avatars and usernames.

This script uses only the Python standard library — no pip install needed.
"""

import json
import os
import re
import sys
import urllib.request

GITHUB_USER = "NhanAZ"
README_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "README.md")
COLUMNS = 5
AVATAR_SIZE = 64

MARKERS_START = "<!-- FOLLOWERS-START -->"
MARKERS_END = "<!-- FOLLOWERS-END -->"


def fetch_all_paginated(url_template: str, username: str, token: str | None = None) -> list[dict]:
    """Fetch all items from a paginated GitHub API endpoint."""
    items = []
    page = 1
    per_page = 100

    while True:
        url = url_template.format(username=username, per_page=per_page, page=page)
        req = urllib.request.Request(url)
        req.add_header("Accept", "application/vnd.github.v3+json")
        req.add_header("User-Agent", f"{username}-readme-updater")
        if token:
            req.add_header("Authorization", f"Bearer {token}")

        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read().decode("utf-8"))

        if not data:
            break

        items.extend(data)
        page += 1

    return items


def fetch_all_followers(username: str, token: str | None = None) -> list[dict]:
    """Fetch all followers."""
    return fetch_all_paginated(
        "https://api.github.com/users/{username}/followers?per_page={per_page}&page={page}",
        username, token,
    )


def fetch_all_following(username: str, token: str | None = None) -> list[dict]:
    """Fetch all users that the given user is following."""
    return fetch_all_paginated(
        "https://api.github.com/users/{username}/following?per_page={per_page}&page={page}",
        username, token,
    )


def generate_followers_table(followers: list[dict], following_logins: set[str]) -> str:
    """Generate an HTML table of followers with avatars.

    Followers that the user follows back (mutual) are listed first,
    both groups sorted alphabetically.
    """
    # Split into mutual follows and one-way followers
    mutual = [f for f in followers if f["login"] in following_logins]
    others = [f for f in followers if f["login"] not in following_logins]

    # Sort mutual follows by account age (lower ID = older account)
    mutual.sort(key=lambda f: f["id"])
    # Sort the rest alphabetically (case-insensitive)
    others.sort(key=lambda f: f["login"].lower())

    # Mutual follows first, then the rest
    sorted_followers = mutual + others

    lines = []
    lines.append(MARKERS_START)
    lines.append("<!-- This section is auto-generated by a GitHub Actions workflow. Do not edit manually. -->")
    lines.append("")
    lines.append(f"**{len(followers)}** amazing people are following me! 🎉 ({len(mutual)} mutual 🤝)")
    lines.append("")
    lines.append("<table>")

    for i in range(0, len(sorted_followers), COLUMNS):
        row = sorted_followers[i : i + COLUMNS]

        # Avatar row
        lines.append("  <tr>")
        for follower in row:
            login = follower["login"]
            avatar = follower["avatar_url"]
            profile = f"https://github.com/{login}"
            is_mutual = login in following_logins
            badge = " 🤝" if is_mutual else ""
            lines.append(
                f'    <td align="center">'
                f'<a href="{profile}">'
                f'<img src="{avatar}" width="{AVATAR_SIZE}" height="{AVATAR_SIZE}" alt="@{login}"/>'
                f"<br />"
                f"<sub><b>@{login}{badge}</b></sub>"
                f"</a>"
                f"</td>"
            )
        lines.append("  </tr>")

    lines.append("</table>")
    lines.append("")
    lines.append(MARKERS_END)

    return "\n".join(lines)


def update_readme(table_content: str) -> bool:
    """Update README.md between the marker comments. Returns True if changed."""
    with open(README_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    pattern = re.compile(
        re.escape(MARKERS_START) + r".*?" + re.escape(MARKERS_END),
        re.DOTALL,
    )

    if pattern.search(content):
        new_content = pattern.sub(table_content, content)
    else:
        print("WARNING: Markers not found in README.md. Cannot update.")
        return False

    if new_content == content:
        print("No changes detected. README is already up to date.")
        return False

    with open(README_PATH, "w", encoding="utf-8") as f:
        f.write(new_content)

    print("README.md updated successfully.")
    return True


def main():
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("Note: GITHUB_TOKEN not set. Using unauthenticated requests (lower rate limit).")

    print(f"Fetching followers for {GITHUB_USER}...")
    followers = fetch_all_followers(GITHUB_USER, token)
    print(f"Found {len(followers)} followers.")

    print(f"Fetching following list for {GITHUB_USER}...")
    following = fetch_all_following(GITHUB_USER, token)
    following_logins = {u["login"] for u in following}
    print(f"Following {len(following_logins)} users.")

    table = generate_followers_table(followers, following_logins)
    changed = update_readme(table)

    if not changed:
        print("No update needed.")
    else:
        print("README.md has been updated with the latest followers.")


if __name__ == "__main__":
    main()
